// One look for every widget, applied once at bring-up.
//
// The scene is near-black with a cool grey grid, and the DATA owns
// warm — a turbo ramp's high end is red. So the chrome is a cool,
// desaturated slate with a single azure accent: a panel that also
// shouts in red makes the reader work out which red is the
// measurement. Nothing here is user-controllable, on purpose. A theme
// that can be edited is a theme every screenshot disagrees about.
//
// The typefaces are embedded from the pinned imgui checkout (Fonts.h is
// generated by CMake), so an installed binary carries its own text and
// reads nothing from disk.

#include "Ui.h"

#include "../core/App.h"

#include <Fonts.h>
#include <imgui.h>
#include <implot.h>
#include <implot3d.h>

namespace sv {
namespace {

// The palette, once. Every colour below is one of these or one of
// these with an alpha — which is what makes it a theme rather than a
// hundred decisions.
constexpr ImVec4 kInk{0.043f, 0.047f, 0.059f, 1.00f};
constexpr ImVec4 kPanel{0.086f, 0.094f, 0.114f, 0.94f};
constexpr ImVec4 kSunken{0.063f, 0.069f, 0.086f, 1.00f};
constexpr ImVec4 kField{0.137f, 0.149f, 0.180f, 1.00f};
constexpr ImVec4 kFieldHot{0.180f, 0.196f, 0.235f, 1.00f};
constexpr ImVec4 kFieldOn{0.220f, 0.243f, 0.290f, 1.00f};
constexpr ImVec4 kEdge{0.196f, 0.212f, 0.255f, 1.00f};
constexpr ImVec4 kText{0.867f, 0.886f, 0.925f, 1.00f};
constexpr ImVec4 kTextDim{0.435f, 0.463f, 0.522f, 1.00f};
constexpr ImVec4 kAccent{0.310f, 0.573f, 0.855f, 1.00f};
constexpr ImVec4 kAccentHot{0.404f, 0.663f, 0.937f, 1.00f};
constexpr ImVec4 kAccentDeep{0.235f, 0.451f, 0.694f, 1.00f};

constexpr ImVec4 fade(ImVec4 c, float a) { return {c.x, c.y, c.z, a}; }

void colours(ImGuiStyle &s) {
    ImVec4 *c = s.Colors;
    c[ImGuiCol_Text] = kText;
    c[ImGuiCol_TextDisabled] = kTextDim;
    c[ImGuiCol_TextSelectedBg] = fade(kAccent, 0.35f);
    c[ImGuiCol_TextLink] = kAccentHot;

    c[ImGuiCol_WindowBg] = kPanel;
    c[ImGuiCol_ChildBg] = fade(kSunken, 0.60f);
    c[ImGuiCol_PopupBg] = fade(kInk, 0.98f);
    c[ImGuiCol_Border] = kEdge;
    c[ImGuiCol_BorderShadow] = fade(kInk, 0.0f);

    c[ImGuiCol_FrameBg] = kField;
    c[ImGuiCol_FrameBgHovered] = kFieldHot;
    c[ImGuiCol_FrameBgActive] = kFieldOn;

    // The title bar reads as part of the panel, not as a separate bar:
    // a strong title is a second thing competing with the scene.
    c[ImGuiCol_TitleBg] = kSunken;
    c[ImGuiCol_TitleBgActive] = kField;
    c[ImGuiCol_TitleBgCollapsed] = fade(kSunken, 0.75f);
    c[ImGuiCol_MenuBarBg] = kSunken;

    c[ImGuiCol_ScrollbarBg] = fade(kInk, 0.0f);
    c[ImGuiCol_ScrollbarGrab] = kFieldHot;
    c[ImGuiCol_ScrollbarGrabHovered] = kFieldOn;
    c[ImGuiCol_ScrollbarGrabActive] = kAccentDeep;

    c[ImGuiCol_CheckMark] = kAccentHot;
    c[ImGuiCol_SliderGrab] = kAccent;
    c[ImGuiCol_SliderGrabActive] = kAccentHot;

    // Buttons are quieter than fields until touched: on a panel of
    // sliders the two or three ACTIONS should not be the loudest thing.
    c[ImGuiCol_Button] = fade(kField, 0.85f);
    c[ImGuiCol_ButtonHovered] = kFieldOn;
    c[ImGuiCol_ButtonActive] = kAccentDeep;

    c[ImGuiCol_Header] = fade(kAccent, 0.22f);
    c[ImGuiCol_HeaderHovered] = fade(kAccent, 0.34f);
    c[ImGuiCol_HeaderActive] = fade(kAccent, 0.46f);

    c[ImGuiCol_Separator] = kEdge;
    c[ImGuiCol_SeparatorHovered] = fade(kAccent, 0.60f);
    c[ImGuiCol_SeparatorActive] = kAccent;

    c[ImGuiCol_ResizeGrip] = fade(kTextDim, 0.25f);
    c[ImGuiCol_ResizeGripHovered] = fade(kAccent, 0.55f);
    c[ImGuiCol_ResizeGripActive] = kAccent;

    c[ImGuiCol_Tab] = fade(kSunken, 0.90f);
    c[ImGuiCol_TabHovered] = kFieldOn;
    c[ImGuiCol_TabSelected] = kField;
    c[ImGuiCol_TabSelectedOverline] = kAccent;
    c[ImGuiCol_TabDimmed] = fade(kSunken, 0.70f);
    c[ImGuiCol_TabDimmedSelected] = fade(kField, 0.80f);
    c[ImGuiCol_TabDimmedSelectedOverline] = fade(kAccent, 0.40f);

    c[ImGuiCol_DockingPreview] = fade(kAccent, 0.45f);
    c[ImGuiCol_DockingEmptyBg] = fade(kInk, 0.0f);

    c[ImGuiCol_PlotLines] = kAccent;
    c[ImGuiCol_PlotLinesHovered] = kAccentHot;
    c[ImGuiCol_PlotHistogram] = kAccent;
    c[ImGuiCol_PlotHistogramHovered] = kAccentHot;

    c[ImGuiCol_TableHeaderBg] = kSunken;
    c[ImGuiCol_TableBorderStrong] = kEdge;
    c[ImGuiCol_TableBorderLight] = fade(kEdge, 0.55f);
    c[ImGuiCol_TableRowBg] = fade(kInk, 0.0f);
    c[ImGuiCol_TableRowBgAlt] = fade(kText, 0.03f);

    c[ImGuiCol_TreeLines] = fade(kEdge, 0.80f);
    c[ImGuiCol_DragDropTarget] = kAccentHot;
    c[ImGuiCol_NavCursor] = kAccent;
    c[ImGuiCol_NavWindowingHighlight] = fade(kText, 0.70f);
    c[ImGuiCol_NavWindowingDimBg] = fade(kInk, 0.55f);
    c[ImGuiCol_ModalWindowDimBg] = fade(kInk, 0.65f);
    c[ImGuiCol_InputTextCursor] = kAccentHot;
}

// Rounding, borders and the space between things. ImGui's defaults are
// tuned for a debug overlay: square, tight, and every control the same
// weight. A control panel a person reads for an hour wants air.
void metrics(ImGuiStyle &s) {
    s.WindowPadding = ImVec2(11.0f, 9.0f);
    s.FramePadding = ImVec2(8.0f, 4.0f);
    s.CellPadding = ImVec2(7.0f, 4.0f);
    s.ItemSpacing = ImVec2(9.0f, 7.0f);
    s.ItemInnerSpacing = ImVec2(7.0f, 5.0f);
    s.IndentSpacing = 18.0f;
    s.ScrollbarSize = 11.0f;
    s.GrabMinSize = 11.0f;

    s.WindowBorderSize = 1.0f;
    s.ChildBorderSize = 1.0f;
    s.PopupBorderSize = 1.0f;
    s.FrameBorderSize = 0.0f;
    s.TabBorderSize = 0.0f;
    s.TabBarBorderSize = 1.0f;
    s.SeparatorTextBorderSize = 1.0f;

    s.WindowRounding = 6.0f;
    s.ChildRounding = 5.0f;
    s.FrameRounding = 4.0f;
    s.PopupRounding = 5.0f;
    s.ScrollbarRounding = 6.0f;
    s.GrabRounding = 5.0f;
    s.TabRounding = 4.0f;

    // A title left-aligned reads as a label on the panel; centred it
    // reads as a heading, which is a weight this content does not have.
    s.WindowTitleAlign = ImVec2(0.0f, 0.5f);
    s.SeparatorTextAlign = ImVec2(0.0f, 0.5f);
    s.SeparatorTextPadding = ImVec2(18.0f, 5.0f);
    s.ButtonTextAlign = ImVec2(0.5f, 0.5f);
    s.SelectableTextAlign = ImVec2(0.0f, 0.5f);

    // Greyed, not ghostly: a disabled control still has to be readable
    // enough to say what it would do.
    s.DisabledAlpha = 0.45f;
    s.WindowMenuButtonPosition = ImGuiDir_None;
    s.AntiAliasedLines = true;
    s.AntiAliasedLinesUseTex = true;
    s.AntiAliasedFill = true;
}

// The series palette, and the one place a data colour is chosen. It
// OPENS on the UI accent, so the first series and the chrome are the
// same blue and a one-series plot needs no legend to be read; the rest
// hold a similar lightness so no series shouts louder than another on
// a dark ground, which is what a qualitative set is for.
//
// A CONTINUOUS field is a different question and gets a different
// answer — see plot_colormap.
constexpr ImVec4 kSeries[] = {
    {0.310f, 0.573f, 0.855f, 1.0f}, // azure, the UI accent
    {0.878f, 0.659f, 0.235f, 1.0f}, // amber
    {0.247f, 0.749f, 0.659f, 1.0f}, // teal
    {0.910f, 0.412f, 0.490f, 1.0f}, // rose
    {0.608f, 0.494f, 0.871f, 1.0f}, // violet
    {0.624f, 0.788f, 0.290f, 1.0f}, // lime
    {0.322f, 0.780f, 0.910f, 1.0f}, // cyan
    {0.851f, 0.502f, 0.353f, 1.0f}, // clay
};

// ImPlot and ImPlot3D keep SEPARATE registries, so the same eight
// colours are added to each — an unregistered 3D plot silently falls
// back to its own defaults, which is how the two libraries drift apart
// while every value in this file looks right.
ImPlotColormap series_colormap() {
    const ImPlotColormap found = ImPlot::GetColormapIndex("simview");
    return found != -1 ? found : ImPlot::AddColormap("simview", kSeries, 8);
}

ImPlot3DColormap series_colormap3() {
    const ImPlot3DColormap found = ImPlot3D::GetColormapIndex("simview");
    return found != -1 ? found : ImPlot3D::AddColormap("simview", kSeries, 8);
}

void plot_theme() {
    ImPlotStyle &p = ImPlot::GetStyle();
    ImVec4 *c = p.Colors;
    c[ImPlotCol_FrameBg] = fade(kInk, 0.0f);
    c[ImPlotCol_PlotBg] = fade(kSunken, 0.65f);
    c[ImPlotCol_PlotBorder] = kEdge;
    // The legend sits ON the data by default, so it is translucent:
    // a reader should be able to see what it covers.
    c[ImPlotCol_LegendBg] = fade(kInk, 0.72f);
    c[ImPlotCol_LegendBorder] = kEdge;
    c[ImPlotCol_LegendText] = kText;
    c[ImPlotCol_TitleText] = kText;
    c[ImPlotCol_InlayText] = kTextDim;
    c[ImPlotCol_AxisText] = kTextDim;
    c[ImPlotCol_AxisGrid] = fade(kEdge, 0.55f);
    c[ImPlotCol_AxisTick] = kEdge;
    c[ImPlotCol_AxisBg] = fade(kInk, 0.0f);
    c[ImPlotCol_AxisBgHovered] = fade(kAccent, 0.20f);
    c[ImPlotCol_AxisBgActive] = fade(kAccent, 0.32f);
    c[ImPlotCol_Selection] = kAccentHot;
    c[ImPlotCol_Crosshairs] = fade(kText, 0.55f);

    // The axis furniture. ImPlot's ticks are 10px long and its labels
    // sit 5px off the frame, which reads as a ruler pressed against the
    // data; short ticks with room around the numbers read as a scale.
    // Tick DENSITY is not ours — ImPlot's locator targets a fixed
    // pixels-per-tick and exposes no knob for it.
    p.PlotPadding = ImVec2(12.0f, 10.0f);
    p.LabelPadding = ImVec2(7.0f, 6.0f);
    p.MajorTickLen = ImVec2(6.0f, 6.0f);
    p.MinorTickLen = ImVec2(3.0f, 3.0f);
    p.MajorTickSize = ImVec2(1.0f, 1.0f);
    p.MinorTickSize = ImVec2(1.0f, 1.0f);
    // A curve that touches the frame reads as clipped. A fitted axis
    // leaves a little room, more above and below than left and right,
    // because that is where a peak lands.
    p.FitPadding = ImVec2(0.02f, 0.07f);
    p.LegendPadding = ImVec2(9.0f, 9.0f);
    p.LegendInnerPadding = ImVec2(6.0f, 4.0f);
    p.PlotBorderSize = 0.0f;
    p.MinorAlpha = 0.18f;
    p.Colormap = series_colormap();

    ImPlot3DStyle &q = ImPlot3D::GetStyle();
    q.LineWeight = 1.75f;
    q.MarkerSize = 3.0f;
    q.FillAlpha = 0.60f;
    q.PlotPadding = ImVec2(11.0f, 9.0f);
    q.Colormap = series_colormap3();
    ImVec4 *d = q.Colors;
    d[ImPlot3DCol_FrameBg] = fade(kInk, 0.0f);
    d[ImPlot3DCol_PlotBg] = fade(kSunken, 0.65f);
    d[ImPlot3DCol_PlotBorder] = kEdge;
    d[ImPlot3DCol_LegendBg] = fade(kInk, 0.72f);
    d[ImPlot3DCol_LegendBorder] = kEdge;
    d[ImPlot3DCol_LegendText] = kText;
    d[ImPlot3DCol_TitleText] = kText;
    d[ImPlot3DCol_InlayText] = kTextDim;
    d[ImPlot3DCol_AxisText] = kTextDim;
    d[ImPlot3DCol_AxisGrid] = fade(kEdge, 0.55f);
    d[ImPlot3DCol_AxisTick] = kEdge;
}

} // namespace

void ui_theme(impl::UiState &ui) {
    ImGuiIO &io = ImGui::GetIO();

    // ImGui 1.92 rasterizes glyphs on demand, so the size is a STYLE
    // number rather than a property of the atlas: one TTF serves every
    // size the UI asks for. The bytes are ours and must not be freed.
    ImFontConfig cfg;
    cfg.FontDataOwnedByAtlas = false;
    cfg.OversampleH = 2;
    cfg.OversampleV = 1;
    io.Fonts->AddFontFromMemoryTTF(const_cast<unsigned char *>(sv_font_sans),
                                   int(sizeof sv_font_sans), 0.0f, &cfg);
    // A second face for NUMBERS. Digits that do not share a width make
    // a column of readouts jump as the last figure changes, which is
    // the one thing a reader is watching for.
    ui.mono = io.Fonts->AddFontFromMemoryTTF(
        const_cast<unsigned char *>(sv_font_mono), int(sizeof sv_font_mono),
        0.0f, &cfg);

    ImGuiStyle &s = ImGui::GetStyle();
    s.FontSizeBase = 16.0f;
    colours(s);
    metrics(s);
    plot_theme();
}

} // namespace sv
