#!/bin/sh
# Regenerate the committed display bytecode (SPIR-V + MSL) from
# display.slang. Dev-only: consumers never need a shader toolchain.
# DXIL (Windows/D3D12) is a planned addition. Deterministic: running
# twice must produce identical bytes — CI-adjacent checks rely on it.
set -eu
cd "$(dirname "$0")"
SLANGC=${SLANGC:-$(command -v slangc || echo /usr/local/bin/slangc)}
[ -x "$SLANGC" ] || { echo "regen: slangc not found"; exit 1; }
OUT=../src/draw/bytecode
mkdir -p "$OUT"

emit() { # name, array-name, file
    printf '// GENERATED by shaders/regen.sh from display.slang — DO NOT EDIT.\n' > "$OUT/$2.h"
    printf '#pragma once\n#include <cstddef>\n' >> "$OUT/$2.h"
    xxd -i -n "$2" "$3" >> "$OUT/$2.h"
}

for e in vsmain fsmain; do
    stage=$([ "$e" = vsmain ] && echo vertex || echo fragment)
    "$SLANGC" display.slang -target spirv -entry $e -stage $stage \
        -fvk-use-entrypoint-name -emit-spirv-directly -o "$e.spv"
    "$SLANGC" display.slang -target metal -entry $e -stage $stage \
        -o "$e.metal"
    emit "$e" "display_${e}_spirv" "$e.spv"
    emit "$e" "display_${e}_msl" "$e.metal"
    rm -f "$e.spv" "$e.metal"
done
echo "regen: bytecode written to $OUT"
