#!/bin/sh
# Regenerate the committed display bytecode (SPIR-V) from
# display.slang. Dev-only: consumers never need a shader toolchain.
# Native MSL and DXIL are a planned addition — both need emission that
# follows SDL's per-stage binding conventions, which slang's defaults
# do not (measured: slang-MSL bound nothing and painted NaN-black).
# Deterministic: running twice must produce identical bytes.
set -eu
cd "$(dirname "$0")"
SLANGC=${SLANGC:-$(command -v slangc || echo /usr/local/bin/slangc)}
[ -x "$SLANGC" ] || { echo "regen: slangc not found"; exit 1; }
# Where a source's bytecode belongs — the stratum that includes it.
out_for() {
    case "$1" in
    cloud | grid3 | axes3 | mesh | cloud_shadow | mesh_shadow)
        echo ../src/world/bytecode ;;
    *) echo ../src/scene/bytecode ;;
    esac
}

emit() { # source-name, array-name, file
    printf '// GENERATED by shaders/regen.sh from %s — DO NOT EDIT.\n' "$1" \
        > "$OUT/$2.h"
    printf '#pragma once\n#include <cstddef>\n' >> "$OUT/$2.h"
    xxd -i -n "$2" "$3" >> "$OUT/$2.h"
}

# One shader, or all of them. Naming one matters: slangc's output is
# only byte-stable for a given slangc, so regenerating everything with
# a newer one diffs bytecode nobody meant to touch.
for src in ${*:-display lines particles cloud grid3 axes3 mesh cloud_shadow mesh_shadow}; do
    OUT=$(out_for "$src")
    mkdir -p "$OUT"
    for e in vsmain fsmain; do
        stage=$([ "$e" = vsmain ] && echo vertex || echo fragment)
        "$SLANGC" "$src.slang" -target spirv -entry $e -stage $stage \
            -fvk-use-entrypoint-name -emit-spirv-directly -o "$e.spv"
        emit "$src.slang" "${src}_${e}_spirv" "$e.spv"
        rm -f "$e.spv"
    done
done
echo "regen: bytecode written"
