#!/bin/sh
# Regenerate the committed display bytecode (SPIR-V) from
# display.slang. Dev-only: consumers never need a shader toolchain.
# Native MSL and DXIL are a planned addition — both need emission that
# follows SDL's per-stage binding conventions, which slang's defaults
# do not (measured: slang-MSL bound nothing and painted NaN-black).
# Deterministic: running twice must produce identical bytes.
set -eu
cd "$(dirname "$0")"
SLANGC=${SLANGC:-$(command -v slangc || echo /usr/local/bin/slangc)}
[ -x "$SLANGC" ] || { echo "regen: slangc not found"; exit 1; }
OUT=../src/draw/bytecode
mkdir -p "$OUT"

emit() { # name, array-name, file
    printf '// GENERATED by shaders/regen.sh from display.slang — DO NOT EDIT.\n' > "$OUT/$2.h"
    printf '#pragma once\n#include <cstddef>\n' >> "$OUT/$2.h"
    xxd -i -n "$2" "$3" >> "$OUT/$2.h"
}

for e in vsmain fsmain; do
    stage=$([ "$e" = vsmain ] && echo vertex || echo fragment)
    "$SLANGC" display.slang -target spirv -entry $e -stage $stage \
        -fvk-use-entrypoint-name -emit-spirv-directly -o "$e.spv"
    emit "$e" "display_${e}_spirv" "$e.spv"
    rm -f "$e.spv"
done
echo "regen: bytecode written to $OUT"
